#!/bin/bash

echo "🔧 Adding Missing OpenPolicy API Container"
echo "========================================="
echo ""

echo "📋 Current Status:"
echo "=================="
echo "✅ Dashboard: http://192.168.2.152:3000 (Working)"
echo "✅ Flower Monitor: http://192.168.2.152:5555 (Working)"
echo "❌ API: http://192.168.2.152:8000 (Missing Container)"
echo ""

echo "🚀 Step-by-Step Instructions:"
echo "============================"
echo ""
echo "1. 📱 Open Container Station:"
echo "   http://192.168.2.152:8080"
echo ""
echo "2. 🐳 Click 'Create' → 'Application'"
echo ""
echo "3. 🔍 Search for this exact image:"
echo "   ashishtandon9/openpolicyashback:latest"
echo ""
echo "4. ⚙️ Configure the container:"
echo "   • Container name: openpolicy_api"
echo "   • Port mapping: 8000:8000"
echo ""
echo "5. 🔧 Environment Variables (Add these one by one):"
echo "   • DB_HOST = openpolicy_postgres"
echo "   • DB_PORT = 5432"
echo "   • DB_NAME = opencivicdata"
echo "   • DB_USER = openpolicy"
echo "   • DB_PASSWORD = openpolicy123"
echo "   • REDIS_URL = redis://openpolicy_redis:6379/0"
echo "   • CORS_ORIGINS = http://192.168.2.152:3000,http://localhost:3000"
echo ""
echo "6. 📁 Volume Mappings (Add these one by one):"
echo "   • /share/Container/openpolicy/regions_report.json:/app/regions_report.json:ro"
echo "   • /share/Container/openpolicy/scrapers:/app/scrapers:ro"
echo ""
echo "7. ✅ Click 'Create'"
echo ""
echo "8. ▶️ Start the container"
echo ""

echo "⏱️ Expected Timeline:"
echo "===================="
echo "• Container startup: 2-3 minutes"
echo "• Database connection: 1-2 minutes"
echo "• Health check: 30 seconds"
echo "• System operational: 5 minutes total"
echo ""

echo "🧪 Test After Creation:"
echo "======================"
echo "1. Test API Health:"
echo "   curl http://192.168.2.152:8000/health"
echo ""
echo "2. Test API Docs:"
echo "   http://192.168.2.152:8000/docs"
echo ""
echo "3. Test Dashboard (should now show real data):"
echo "   http://192.168.2.152:3000"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ API responds at http://192.168.2.152:8000/health"
echo "✅ Dashboard loads real data"
echo "✅ Flower monitor shows active tasks"
echo "✅ All containers in 'Running' status"
echo ""

echo "📊 After API is Working:"
echo "======================="
echo "• First data scraping: 15-30 minutes"
echo "• Complete data collection: 2-4 hours"
echo "• Real-time updates: Continuous"
echo ""

echo "🚀 Ready to add the API container!"
echo "Follow the steps above and your OpenPolicy system will be complete!" 