#!/bin/bash

echo "🔧 Fixing Missing OpenPolicy API Container"
echo "========================================="

QNAP_HOST="192.168.2.152"
QNAP_USER="ashish101"

echo "📋 Current Status Analysis:"
echo "=========================="
echo "✅ Dashboard: Working (Port 3000)"
echo "✅ Flower Monitor: Working (Port 5555)"
echo "❌ API: Missing (Port 8000)"
echo "❌ Database: Not responding properly"
echo "❌ Redis: Not responding properly"

echo ""
echo "🔍 Issue Identified:"
echo "==================="
echo "The openpolicy_api container is missing from Container Station."
echo "This is why the API is not responding on port 8000."

echo ""
echo "🚀 Solution: Add Missing API Container"
echo "====================================="
echo ""
echo "Please follow these steps in Container Station:"
echo ""
echo "1. Open Container Station: http://192.168.2.152:8080"
echo ""
echo "2. Click 'Create' → 'Application'"
echo ""
echo "3. Search for: ashishtandon9/openpolicyashback:latest"
echo ""
echo "4. Configure the API container:"
echo "   - Container name: openpolicy_api"
echo "   - Port mapping: 8000:8000"
echo "   - Environment variables:"
echo "     DB_HOST=openpolicy_postgres"
echo "     DB_PORT=5432"
echo "     DB_NAME=opencivicdata"
echo "     DB_USER=openpolicy"
echo "     DB_PASSWORD=openpolicy123"
echo "     REDIS_URL=redis://openpolicy_redis:6379/0"
echo "     CORS_ORIGINS=http://192.168.2.152:3000,http://localhost:3000"
echo ""
echo "5. Volume mappings:"
echo "     /share/Container/openpolicy/regions_report.json:/app/regions_report.json:ro"
echo "     /share/Container/openpolicy/scrapers:/app/scrapers:ro"
echo ""
echo "6. Click 'Create'"
echo ""
echo "7. Start the container"
echo ""

echo "📊 Expected Timeline After Fix:"
echo "=============================="
echo "• API container startup: 2-3 minutes"
echo "• Database connection: 1-2 minutes"
echo "• Health check response: 30 seconds"
echo "• Full system operational: 5 minutes"
echo "• First data scraping: 15-30 minutes"
echo "• Complete data collection: 2-4 hours"

echo ""
echo "🌐 URLs to Test After Fix:"
echo "========================="
echo "• API Health: http://192.168.2.152:8000/health"
echo "• API Docs: http://192.168.2.152:8000/docs"
echo "• Dashboard: http://192.168.2.152:3000"
echo "• Flower Monitor: http://192.168.2.152:5555"

echo ""
echo "✅ Once the API container is added and running,"
echo "   your OpenPolicy system will be fully operational!" 