#!/bin/bash

echo "🔄 Recreating Container Station Application"
echo "=========================================="
echo ""

echo "📋 Current Status:"
echo "=================="
echo "✅ Configuration files updated correctly"
echo "✅ API service defined in docker-compose.yml"
echo "❌ API container still not starting"
echo ""

echo "🚀 Solution: Recreate the Application"
echo "===================================="
echo ""
echo "Sometimes Container Station needs the application to be completely"
echo "recreated rather than just restarted. Here's what to do:"
echo ""
echo "1. 📱 Open Container Station:"
echo "   http://192.168.2.152:8080"
echo ""
echo "2. 🔍 Find your OpenPolicy application"
echo "   - Look for the docker-compose application"
echo "   - Note which containers are currently running"
echo ""
echo "3. ⏹️ Stop the Application:"
echo "   - Click on the application"
echo "   - Click 'Stop' or 'Stop All'"
echo "   - Wait for all containers to stop"
echo ""
echo "4. 🗑️ Delete the Application:"
echo "   - Click on the application"
echo "   - Click 'Delete' or 'Remove'"
echo "   - Confirm deletion"
echo "   - This will NOT delete your data (it's in volumes)"
echo ""
echo "5. 🆕 Create New Application:"
echo "   - Click 'Create' → 'Application'"
echo "   - Click 'Import from docker-compose.yml'"
echo "   - Upload: /share/Container/openpolicy/docker-compose.yml"
echo "   - Click 'Create'"
echo ""
echo "6. ▶️ Start the New Application:"
echo "   - Click 'Start' or 'Start All'"
echo "   - Wait 3-5 minutes for all containers to start"
echo ""
echo "7. ✅ Verify All Containers:"
echo "   - Check that ALL containers are running:"
echo "     • openpolicy_postgres"
echo "     • openpolicy_redis"
echo "     • openpolicy_api"
echo "     • openpolicy_worker"
echo "     • openpolicy_beat"
echo "     • openpolicy_flower"
echo "     • openpolicy_dashboard"
echo ""

echo "⏱️ Expected Timeline:"
echo "===================="
echo "• Stop application: 1-2 minutes"
echo "• Delete application: 30 seconds"
echo "• Create new application: 1-2 minutes"
echo "• Start all containers: 3-5 minutes"
echo "• API container startup: 2-3 minutes"
echo "• Total time: 8-12 minutes"
echo ""

echo "🧪 Test After Recreation:"
echo "========================"
echo "1. Test API Health:"
echo "   curl http://192.168.2.152:8000/health"
echo ""
echo "2. Test API Docs:"
echo "   http://192.168.2.152:8000/docs"
echo ""
echo "3. Test Dashboard:"
echo "   http://192.168.2.152:3000"
echo ""
echo "4. Run Full Validation:"
echo "   ./final-validation.sh"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ All 7 containers in 'Running' status"
echo "✅ API responds at http://192.168.2.152:8000/health"
echo "✅ Dashboard loads real data"
echo "✅ Flower monitor shows active tasks"
echo ""

echo "📊 After Recreation:"
echo "==================="
echo "• First data scraping: 15-30 minutes"
echo "• Complete collection: 2-4 hours"
echo "• Real-time updates: Continuous"
echo ""

echo "🚀 Ready to recreate!"
echo "This will ensure all containers start properly." 