#!/bin/bash

echo "🔄 Restarting Container Station Application"
echo "=========================================="
echo ""

QNAP_HOST="192.168.2.152"
QNAP_USER="ashish101"

echo "📋 Current Status:"
echo "=================="
echo "✅ Docker-compose file updated with API service"
echo "✅ Configuration files in place"
echo "❌ API container not running"
echo ""

echo "🚀 Manual Restart Required:"
echo "=========================="
echo ""
echo "Since Container Station is a web-based interface, you need to:"
echo ""
echo "1. 📱 Open Container Station:"
echo "   http://192.168.2.152:8080"
echo ""
echo "2. 🔍 Find your OpenPolicy application"
echo "   - Look for the docker-compose application"
echo "   - It should show some containers running"
echo ""
echo "3. ⏹️ Stop the Application:"
echo "   - Click on the application"
echo "   - Click 'Stop' or 'Stop All'"
echo "   - Wait for all containers to stop"
echo ""
echo "4. ▶️ Start the Application:"
echo "   - Click 'Start' or 'Start All'"
echo "   - This will start ALL containers including the API"
echo "   - Wait 2-3 minutes for startup"
echo ""
echo "5. ✅ Verify API is Running:"
echo "   - Check that 'openpolicy_api' appears in the container list"
echo "   - Test: http://192.168.2.152:8000/health"
echo ""

echo "⏱️ Expected Timeline:"
echo "===================="
echo "• Stop application: 1-2 minutes"
echo "• Start application: 2-3 minutes"
echo "• API container startup: 1-2 minutes"
echo "• Health check: 30 seconds"
echo "• Total time: 5-8 minutes"
echo ""

echo "🧪 Test Commands (run after restart):"
echo "===================================="
echo "ssh ashish101@192.168.2.152 'curl -s http://localhost:8000/health'"
echo "ssh ashish101@192.168.2.152 './final-validation.sh'"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ API responds at http://192.168.2.152:8000/health"
echo "✅ Dashboard loads real data"
echo "✅ All containers in 'Running' status"
echo "✅ Flower monitor shows active tasks"
echo ""

echo "📊 After Restart:"
echo "================"
echo "• First data scraping: 15-30 minutes"
echo "• Complete collection: 2-4 hours"
echo "• Real-time updates: Continuous"
echo ""

echo "🚀 Ready to restart!"
echo "Follow the steps above to complete your OpenPolicy system!" 