#!/bin/bash

echo "🔧 Restarting Container with Fixed Database"
echo "=========================================="
echo ""

echo "📋 Issue Identified and Fixed:"
echo "=============================="
echo "❌ Database initialization error: 'engine' not found"
echo "✅ Fixed database configuration"
echo "✅ Added engine export to config.py"
echo "✅ New Docker image built and pushed"
echo ""

echo "🚀 Restart Instructions:"
echo "======================="
echo ""
echo "1. 📱 Open Container Station:"
echo "   http://192.168.2.152:8080"
echo ""
echo "2. 🔍 Find your OpenPolicy application"
echo "   - Look for 'OpenPolicyAshBack' application"
echo ""
echo "3. ⏹️ Stop the Application:"
echo "   - Click on the application"
echo "   - Click 'Stop'"
echo "   - Wait for container to stop"
echo ""
echo "4. 🔄 Update the Container:"
echo "   - Click on the application"
echo "   - Click 'Update' or 'Recreate'"
echo "   - This will pull the latest fixed image"
echo "   - Wait for update to complete"
echo ""
echo "5. ▶️ Start the Application:"
echo "   - Click 'Start'"
echo "   - Wait 2-3 minutes for startup"
echo ""

echo "⏱️ Expected Timeline:"
echo "===================="
echo "• Stop application: 1 minute"
echo "• Update container: 2-3 minutes"
echo "• Start application: 2-3 minutes"
echo "• Database init: 30 seconds"
echo "• API ready: 1 minute"
echo "• Total time: 6-8 minutes"
echo ""

echo "🧪 Test After Restart:"
echo "====================="
echo "1. Test API Health:"
echo "   curl http://192.168.2.152:8000/health"
echo ""
echo "2. Test API Docs:"
echo "   http://192.168.2.152:8000/docs"
echo ""
echo "3. Test Dashboard:"
echo "   http://192.168.2.152:3000"
echo ""
echo "4. Test Flower Monitor:"
echo "   http://192.168.2.152:5555"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ Container status: 'Running'"
echo "✅ API responds at http://192.168.2.152:8000/health"
echo "✅ Dashboard loads at http://192.168.2.152:3000"
echo "✅ Flower monitor accessible at http://192.168.2.152:5555"
echo "✅ No database initialization errors in logs"
echo ""

echo "📊 After Restart:"
echo "================"
echo "• Database will be initialized with SQLite"
echo "• All services will start properly"
echo "• First data scraping: 15-30 minutes"
echo "• Complete setup: 2-4 hours"
echo ""

echo "🚀 Ready to restart!"
echo "The database initialization error has been fixed." 