#!/bin/bash

echo "🔧 Updating QNAP with Fixed API Image"
echo "===================================="
echo ""

echo "📋 Issue Identified and Fixed:"
echo "=============================="
echo "❌ GraphQL schema error in API container"
echo "✅ Fixed missing @strawberry.type decorators"
echo "✅ Fixed missing @strawberry.input decorators"
echo "✅ New Docker image built and pushed"
echo ""

echo "🚀 Updating QNAP Server:"
echo "========================"
echo ""

echo "1. 📱 Open Container Station:"
echo "   http://192.168.2.152:8080"
echo ""

echo "2. 🔍 Find your OpenPolicy application"
echo "   - Look for the docker-compose application"
echo ""

echo "3. ⏹️ Stop the Application:"
echo "   - Click on the application"
echo "   - Click 'Stop' or 'Stop All'"
echo "   - Wait for all containers to stop"
echo ""

echo "4. 🔄 Update the API Container:"
echo "   - Find the 'openpolicy_api' container"
echo "   - Click on it"
echo "   - Click 'Update' or 'Recreate'"
echo "   - This will pull the latest fixed image"
echo ""

echo "5. ▶️ Start the Application:"
echo "   - Click 'Start' or 'Start All'"
echo "   - Wait 2-3 minutes for startup"
echo ""

echo "6. ✅ Verify API is Working:"
echo "   - Check that 'openpolicy_api' is running"
echo "   - Test: http://192.168.2.152:8000/health"
echo ""

echo "⏱️ Expected Timeline:"
echo "===================="
echo "• Stop application: 1-2 minutes"
echo "• Update API container: 1-2 minutes"
echo "• Start application: 2-3 minutes"
echo "• API startup: 1-2 minutes"
echo "• Total time: 5-9 minutes"
echo ""

echo "🧪 Test After Update:"
echo "===================="
echo "1. Test API Health:"
echo "   curl http://192.168.2.152:8000/health"
echo ""
echo "2. Test API Docs:"
echo "   http://192.168.2.152:8000/docs"
echo ""
echo "3. Test Dashboard:"
echo "   http://192.168.2.152:3000"
echo ""
echo "4. Run Full Validation:"
echo "   ./final-validation.sh"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ API responds at http://192.168.2.152:8000/health"
echo "✅ All containers in 'Running' status"
echo "✅ Dashboard loads real data"
echo "✅ Flower monitor shows active tasks"
echo ""

echo "📊 After API is Working:"
echo "======================="
echo "• First data scraping: 15-30 minutes"
echo "• Complete collection: 2-4 hours"
echo "• Real-time updates: Continuous"
echo ""

echo "🚀 Ready to update!"
echo "The GraphQL schema error has been fixed in the new image." 